<?php
/**就餐地点控制器
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/11/9
 * Time: 16:29
 */


namespace Admin\Controller;

use Common\Controller\AdminbaseController;

class RestaurantController extends AdminbaseController{

    private $restaurant_model;


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->restaurant_model = D("Common/restaurant");
    }

    public function index(){

        $restaurant = $this->restaurant_model->select();
        $this->assign("restaurant",$restaurant);
        $this->display();
    }

    public function add(){
        $this->display();
    }


    public function add_post(){
        if(IS_POST){
            if ($this->restaurant_model->create()!==false){
                if ($this->restaurant_model->add()!==false) {
                    $this->success(L('ADD_SUCCESS'), U("restaurant/index"));
                } else {
                    $this->error(L('ADD_FAILED'));
                }
            } else {
                $this->error($this->restaurant_model->getError());
            }

        }
    }


    public function edit(){
        $id=I("get.id",0,'intval');
        $restaurant=$this->restaurant_model->where(array('r_id'=>$id))->find();
        $this->assign($restaurant);
        $this->display();
    }


    public function edit_post(){
        if (IS_POST) {
            if ($this->restaurant_model->create()!==false) {
                if ($this->restaurant_model->save()!==false) {
                    $this->success("保存成功！", U("restaurant/index"));
                } else {
                    $this->error("保存失败！");
                }
            } else {
                $this->error($this->restaurant_model->getError());
            }
        }
    }


    public function delete(){
        $id = I("get.id",0,"intval");
        if ($this->restaurant_model->delete($id)!==false) {
            $this->success("删除成功！");
        } else {
            $this->error("删除失败！");
        }
    }
}